name: pr_10
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
